extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
  indentation:
    indent-sequences: consistent

ignore: |
  .venv/
  venv/
  __pycache__/
  node_modules/
  .git/

