codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
        base: auto
    patch:
      default:
        target: 60%
        threshold: 5%

comment:
  layout: "reach, diff, flags, files"
  behavior: default

ignore:
  - "tests/**"
  - "docs/**"
  - "webapp/**"

