name: "Enforce required check: Dangerous deletes guard"

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  protect:
    name: "Apply branch protection (requires PAT)"
    runs-on: ubuntu-latest
    steps:
      - name: Validate token
        shell: bash
        run: |
          if [ -z "${{ secrets.REPO_ADMIN_TOKEN }}" ]; then
            echo "::error::Missing secret REPO_ADMIN_TOKEN with admin:repo scope"
            exit 1
          fi
      - name: Require safety-guard check on default branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.REPO_ADMIN_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const { data: repoInfo } = await github.rest.repos.get({ owner, repo });
            const branch = repoInfo.default_branch || 'main';
            const req = {
              owner,
              repo,
              branch,
              required_status_checks: {
                strict: true,
                contexts: [
                  'CI / 🧯 Dangerous deletes guard',
                  'CI / safety-guard'
                ]
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1
              },
              restrictions: null
            };
            try {
              await github.request('PUT /repos/{owner}/{repo}/branches/{branch}/protection', req);
              core.info(`Branch protection applied on ${branch}`);
            } catch (e) {
              core.setFailed(`Failed to update branch protection on ${branch}: ${e.message}`);
            }

