name: Dependabot notify

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review]

jobs:
  notify-dependabot:
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels: ['dependabot', 'needs-manual-approval']
            });
      - name: Ping maintainer
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: 'תזכורת: PR של Dependabot מחכה לאישור ידני. @amirbiron'
            });